"""
NEPSIM AI Analysis App — SQLModel database models.

Tables:
- ai_analyses : Generated AI feedback stored per completed simulation
"""
from datetime import datetime
from enum import Enum
from typing import Optional
from sqlmodel import Field, SQLModel


class AnalysisStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class AIAnalysisBase(SQLModel):
    simulation_id: int = Field(
        foreign_key="simulations.id",
        unique=True,
        index=True,
        description="One AI analysis record per completed simulation",
    )
    user_id: int = Field(foreign_key="user.id", index=True)
    status: AnalysisStatus = Field(default=AnalysisStatus.PENDING)

    # ── Performance Metrics ────────────────────────────────────────────────
    total_pnl: Optional[float] = Field(default=None, description="Total P&L in NPR")
    total_pnl_pct: Optional[float] = Field(default=None, description="Total return %")
    win_rate: Optional[float] = Field(default=None, description="Win rate 0.0–1.0")
    sharpe_ratio: Optional[float] = Field(default=None)
    max_drawdown: Optional[float] = Field(default=None, description="Max drawdown %")
    total_trades: Optional[int] = Field(default=None)
    winning_trades: Optional[int] = Field(default=None)
    losing_trades: Optional[int] = Field(default=None)
    best_trade_pnl: Optional[float] = Field(default=None, description="Best single trade P&L in NPR")
    worst_trade_pnl: Optional[float] = Field(default=None, description="Worst single trade P&L in NPR")
    avg_holding_days: Optional[float] = Field(default=None)

    # ── Benchmark Comparisons ─────────────────────────────────────────────
    market_return_pct: Optional[float] = Field(
        default=None,
        description="NEPSE index return over same simulation period (%)",
    )
    buy_hold_return_pct: Optional[float] = Field(
        default=None,
        description="Return of a simple buy-and-hold of all purchased stocks (%)",
    )

    # ── LLM-Generated Narrative (JSON blobs) ──────────────────────────────
    # Each field stores the full LLM response section as a JSON string.
    summary_narrative: Optional[str] = Field(
        default=None,
        description="Overall performance summary generated by LLM",
    )
    what_you_did_right: Optional[str] = Field(
        default=None,
        description="JSON list of positive decisions with AI commentary",
    )
    what_you_did_wrong: Optional[str] = Field(
        default=None,
        description="JSON list of mistakes with empathetic explanations",
    )
    what_you_could_have_done: Optional[str] = Field(
        default=None,
        description="JSON list of counterfactual alternatives with actionable advice",
    )
    trade_by_trade_commentary: Optional[str] = Field(
        default=None,
        description="JSON array — one comment per trade in chronological order",
    )

    # ── Skill Scores (0–100) ──────────────────────────────────────────────
    timing_score: Optional[int] = Field(default=None, description="Entry/exit timing quality 0-100")
    selection_score: Optional[int] = Field(default=None, description="Stock selection quality 0-100")
    risk_score: Optional[int] = Field(default=None, description="Risk management quality 0-100")
    patience_score: Optional[int] = Field(default=None, description="Conviction/patience rating 0-100")

    # ── Meta ──────────────────────────────────────────────────────────────
    llm_provider: Optional[str] = Field(
        default=None,
        max_length=50,
        description="LLM used: openai | anthropic | fallback",
    )
    failure_reason: Optional[str] = Field(default=None, max_length=500)


class AIAnalysis(AIAnalysisBase, table=True):
    __tablename__ = "ai_analyses"  # type: ignore

    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = Field(default=None)
